project_id = "ddocrldftvwzjdnitmzz"

[functions.send-ticket-confirmation]
verify_jwt = false

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-pay]
enabled = true
verify_jwt = true
import_map = "./functions/mpesa-pay/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mpesa-pay/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mpesa-pay/*.html" ]

[functions.stripe-checkout]
enabled = true
verify_jwt = true
import_map = "./functions/stripe-checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-checkout/*.html" ]
